import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ClinicModel(props) {
  const { nodes, materials } = useGLTF(
    "/models/clinic.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
        <group position={[-958.2, -34.45, -12.63]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials["Color_-_Ice"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_5.geometry}
            material={materials["Color_-_Oyster"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_10.geometry}
            material={materials["Color_-_Antique"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_13.geometry}
            material={materials.Antique}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_16.geometry}
            material={materials.Casey_Selection}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_20.geometry}
            material={materials.material_0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_21.geometry}
            material={materials["Color_-_Snow_Whi"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_22.geometry}
            material={materials["Color_-_Snow_Whi"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_23.geometry}
            material={materials["Color_-_Snow_Whi"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_24.geometry}
            material={materials["Color_-_Snow_Whi"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_25.geometry}
            material={materials["Color_-_Snow_Whi"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_26.geometry}
            material={materials["Color_-_Snow_Whi"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_27.geometry}
            material={materials["Color_-_Snow_Whi"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_28.geometry}
            material={materials["Color_-_Snow_Whi"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_29.geometry}
            material={materials["Color_-_Snow_Whi"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_30.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_31.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_32.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_33.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_34.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_35.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_36.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_37.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_38.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_39.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_40.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_41.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_42.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_43.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_44.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_45.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_46.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_47.geometry}
            material={materials["Color_-_Neutral"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_49.geometry}
            material={materials.Metal__Steel_Po}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_50.geometry}
            material={materials.Metal__Steel_Po}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_51.geometry}
            material={materials.Metal__Steel_Po}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_52.geometry}
            material={materials.Metal__Steel_Po}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_53.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_54.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_55.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_56.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_57.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_58.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_59.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_60.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_61.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_62.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_63.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_64.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_65.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_66.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_67.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_68.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_69.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_70.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_71.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_72.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_73.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_74.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_75.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_76.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_77.geometry}
            material={materials.Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_78.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_79.geometry}
            material={materials.Glass__Standard}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_80.geometry}
            material={materials.Lace}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_81.geometry}
            material={materials.Metal__Steel_P1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_82.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_83.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_84.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_85.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_86.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_87.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_88.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_89.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_90.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_91.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_92.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_93.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_94.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_95.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_96.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_97.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_98.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_99.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_100.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_101.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_102.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_103.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_104.geometry}
            material={materials.Aluminum_Brushed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_125.geometry}
            material={materials.Drywall}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_126.geometry}
            material={materials.Drywall}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_136.geometry}
            material={materials["Color_-_Bone"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_137.geometry}
            material={materials["Color_-_Bone"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_138.geometry}
            material={materials["Color_-_Bone"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_139.geometry}
            material={materials["Color_-_Bone"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_140.geometry}
            material={materials["Color_-_Bone"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_141.geometry}
            material={materials["Color_-_Bone"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_142.geometry}
            material={materials["Color_-_Bone"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_143.geometry}
            material={materials["Color_-_Bone"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_144.geometry}
            material={materials["Color_-_Bone"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_145.geometry}
            material={materials["Color_-_Bone"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_146.geometry}
            material={materials["Color_-_Bone"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_147.geometry}
            material={materials["Color_-_Bone"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_148.geometry}
            material={materials["Color_-_Bone"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_150.geometry}
            material={materials.Chrome_Polished}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_171.geometry}
            material={materials["Delta_-_Allora_2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_172.geometry}
            material={materials["Delta_-_Allora_S"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_173.geometry}
            material={materials["Delta_-_Allora_S"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_175.geometry}
            material={materials["Color_-_Brite"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_176.geometry}
            material={materials["Color_-_Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_177.geometry}
            material={materials["Color_-_Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_178.geometry}
            material={materials["Color_-_Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_179.geometry}
            material={materials["Color_-_Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_180.geometry}
            material={materials["Color_-_Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_181.geometry}
            material={materials["Color_-_White"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_182.geometry}
            material={materials.Storm}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_183.geometry}
            material={materials.Storm}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_184.geometry}
            material={materials.Stainless_Steel}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_185.geometry}
            material={materials.Stainless_Steel}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_187.geometry}
            material={materials.Foam_Underlaymen}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_193.geometry}
            material={materials.Color_Brown_Dul}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_194.geometry}
            material={materials.Metal__Steel}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_195.geometry}
            material={materials.Metal__Steel}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_196.geometry}
            material={materials.Metal__Steel}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_197.geometry}
            material={materials.Metal__Steel}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_198.geometry}
            material={materials.Metal__Steel}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_199.geometry}
            material={materials.Metal__Steel}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_200.geometry}
            material={materials.Bright}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_201.geometry}
            material={materials.Electric}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_202.geometry}
            material={materials.Light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_203.geometry}
            material={materials.Light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_204.geometry}
            material={materials.Periwinkle}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_205.geometry}
            material={materials["Color_-_Almost_G"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_206.geometry}
            material={materials["Color_-_Almost_G"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_207.geometry}
            material={materials["Color_-_Almost_G"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_208.geometry}
            material={materials["Color_-_Almost_G"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_209.geometry}
            material={materials["Color_-_Almost_G"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_210.geometry}
            material={materials["Color_-_Almost_G"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_211.geometry}
            material={materials["Color_-_Contract"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_212.geometry}
            material={materials.Lighting__Cerami}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_213.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_214.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_215.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_216.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_217.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_218.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_219.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_220.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_221.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_222.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_223.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_224.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_225.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_226.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_227.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_228.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_229.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_230.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_231.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_232.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_233.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_234.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_235.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_236.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_237.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_238.geometry}
            material={materials.Charcoal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_239.geometry}
            material={materials.Cinnamon}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_240.geometry}
            material={materials.Fresh}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_242.geometry}
            material={materials.Brushed_Aluminum}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_243.geometry}
            material={materials.Brushed_Aluminum}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_244.geometry}
            material={materials.Brushed_Aluminum}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_245.geometry}
            material={materials.Brushed_Aluminum}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_246.geometry}
            material={materials.Brushed_Aluminum}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_247.geometry}
            material={materials.Brushed_Aluminum}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_248.geometry}
            material={materials.Dover}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_250.geometry}
            material={materials.Backerboard_14}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_253.geometry}
            material={materials["Color_-_Dark"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_254.geometry}
            material={materials["Color_-_Dark"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_255.geometry}
            material={materials["Color_-_Dark"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_257.geometry}
            material={materials.Mirror}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_259.geometry}
            material={materials.Nickel_Polished}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_260.geometry}
            material={materials.Color_Grey__Char}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_261.geometry}
            material={materials["Color_-_Coal"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_263.geometry}
            material={materials.Metal__Steel_Du}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_264.geometry}
            material={materials.Metal__Steel_Du}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_265.geometry}
            material={materials.Copper_Polished}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_266.geometry}
            material={materials.Copper_Polished}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_271.geometry}
            material={materials["Color_-_Slate"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_3.geometry}
            material={materials["500_touchpad_dis"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_12.geometry}
            material={materials.M3_MIDMARK_LABLE}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials["Light_-_MP_Plank"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_9.geometry}
            material={materials.Brazilian_Cherr1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials["WEATHER_CHANNEL-"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_11.geometry}
            material={materials.M3_DISPLAY}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_7.geometry}
            material={materials.Brazilian_Cherr2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_17.geometry}
            material={materials.Alexa_Meade_Lady}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_15.geometry}
            material={materials.M11_Warning}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_14.geometry}
            material={materials.M11_Display}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_18.geometry}
            material={materials.Lauren_Barksdal1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_48.geometry}
            material={materials.Cygnus_Pearl}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_105.geometry}
            material={materials.White_Tile}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_19.geometry}
            material={materials.Lauren_Barksdale}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_107.geometry}
            material={materials["GEOMETRIC_GREY-B"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_108.geometry}
            material={materials["GEOMETRIC_GREY-B"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_109.geometry}
            material={materials["GEOMETRIC_GREY-B"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_118.geometry}
            material={materials["GEOMETRIC-GREEN"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_119.geometry}
            material={materials["GEOMETRIC-GREEN"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_120.geometry}
            material={materials.Paisley_Teal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_121.geometry}
            material={materials.Paisley_Teal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_106.geometry}
            material={materials.SoapStone}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_127.geometry}
            material={materials.Fir_Stud_16_OC}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_268.geometry}
            material={materials.Fir_Stud_24_OC}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_122.geometry}
            material={materials.Geo_Fabric_Yello}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_123.geometry}
            material={materials.Geo_Fabric_Yello}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_128.geometry}
            material={materials["6201_Sandcrete"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_129.geometry}
            material={materials["6201_Sandcrete"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_130.geometry}
            material={materials["6201_Sandcrete"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_131.geometry}
            material={materials["6201_Sandcrete"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_132.geometry}
            material={materials["6201_Sandcrete"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_133.geometry}
            material={materials["6201_Sandcrete"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_134.geometry}
            material={materials["6201_Sandcrete"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_135.geometry}
            material={materials["6201_Sandcrete"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_149.geometry}
            material={materials.Limestone_5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_114.geometry}
            material={materials.unnamed_model_SK}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_115.geometry}
            material={materials.unnamed_model_SK}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_116.geometry}
            material={materials.unnamed_model_SK}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_117.geometry}
            material={materials.unnamed_model_SK}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_174.geometry}
            material={materials.Brazilian_Cherry}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_124.geometry}
            material={materials.Birch_honey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_188.geometry}
            material={materials.Wood_Tile_Spruce}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_192.geometry}
            material={materials.Birch_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_190.geometry}
            material={materials.MOHAWK_MUITNER_R}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_110.geometry}
            material={materials.unnamed_model_S1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_111.geometry}
            material={materials.unnamed_model_S1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_112.geometry}
            material={materials.unnamed_model_S1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_113.geometry}
            material={materials.unnamed_model_S1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_241.geometry}
            material={materials.Telephone_Displa}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_186.geometry}
            material={materials.LOGO}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_256.geometry}
            material={materials["Eaglesoft-1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_191.geometry}
            material={materials.Limestone_tiles}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_249.geometry}
            material={materials.windows_desktop}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_258.geometry}
            material={materials["2021_Mirror_Alum"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_252.geometry}
            material={materials.Kandinsky}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_262.geometry}
            material={materials["Greystoke-Marble"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_189.geometry}
            material={materials["OSB-Hrz"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_269.geometry}
            material={materials.Housewrap}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_267.geometry}
            material={materials.csv20007_2029t}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_251.geometry}
            material={materials.Thinset_Mortar}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_151.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_152.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_153.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_154.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_155.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_156.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_157.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_158.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_159.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_160.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_161.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_162.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_163.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_164.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_165.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_166.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_167.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_168.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_169.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_170.geometry}
            material={materials["Delta_-_Allora_1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_272.geometry}
            material={materials.Mahogany}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_270.geometry}
            material={materials.Red5_Brick}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/16_treatment_room_3-d_dental_office.glb");