import Head from 'next/head'
import { Suspense } from 'react'
import { Canvas } from '@react-three/fiber';
import {ClinicModel} from '../src/components/ClinicModel';
import { PerspectiveCamera } from '@react-three/drei';

import styles from '../styles/Home.module.css'
import { OrbitControls } from '@react-three/drei';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Life Verse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback={'loading'}>
      <main className={styles.main}>
        <Canvas >
          <gridHelper />
          <axesHelper/>
          <ClinicModel/>
   <ambientLight intensity={1} />
          <OrbitControls />
          <PerspectiveCamera />
        </Canvas>
      </main>
      </Suspense>
    </div>
  )
}
