import Head from "next/head";
import { Suspense } from "react";
import { Canvas } from "@react-three/fiber";
import { OrbitControls, Loader, softShadows, Sky } from "@react-three/drei";
import { ClinicModel } from "../src/components/ClinicModel";
import { Ground } from "../src/components/Ground";
import Character from "../src/components/Character";
import styles from "../styles/Home.module.css";
import * as THREE from "three";
softShadows();
export default function Home() {
  const fov = 60;
  const aspect = 1920 / 1080;
  const near = 2.0;
  const far = 1000.0;
  const camera = new THREE.PerspectiveCamera(fov, aspect, near, far);
  camera.position.set(25, 1220, 25);
  return (
    <div className={styles.container}>
      <Head>
        <title>Life Verse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback={null}>
        <main className={styles.main}>
          <Canvas camera={camera}>
            <gridHelper />
            <axesHelper />
            <OrbitControls />
            <ClinicModel />
            <Ground />
            <perspectiveCamera {...camera} />
            <Character camera={camera} />
            <ambientLight intensity={1} />
            <Sky distance={450000} sunPosition={[5, 1, 8]} inclination={0} azimuth={0.25} />
          </Canvas>
        </main>
      </Suspense>
      <Loader dataInterpolation={(p) => `Loading ${p.toFixed(2)}%`} initialState={(active) => active} />
    </div>
  );
}
